# Generated by Django 4.1.6 on 2023-02-13 19:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilmWork',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Date of change')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='record ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title film')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description film')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date film')),
                ('rating', models.FloatField(verbose_name='Rating')),
                ('type', models.TextField(blank=True, null=True, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'film',
                'verbose_name_plural': 'films',
                'db_table': 'content"."film_work',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Date of change')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='record ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name genre')),
                ('description', models.TextField(blank=True, verbose_name='Description genre')),
            ],
            options={
                'verbose_name': 'genre',
                'verbose_name_plural': 'genres',
                'db_table': 'content"."genre',
            },
        ),
        migrations.CreateModel(
            name='GenreFilmWork',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='record ID')),
            ],
            options={
                'verbose_name': 'title',
                'verbose_name_plural': 'title',
                'db_table': 'content"."genre_film_work',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Date of change')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='record ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full name person')),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'persons',
                'db_table': 'content"."person',
            },
        ),
        migrations.CreateModel(
            name='PersonFilmWork',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='record ID')),
                ('role', models.TextField(blank=True, choices=[('regisseur', 'regisseur'), ('screenwriter', 'screenwriter'), ('actor', 'actor')], null=True, verbose_name='Role')),
                ('film_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.filmwork', verbose_name='Film work')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.person', verbose_name='Person')),
            ],
            options={
                'verbose_name': "The actor's connection to the film",
                'verbose_name_plural': "The actor's connection with films",
                'db_table': 'content"."person_film_work',
            },
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['full_name'], name='person_idx'),
        ),
        migrations.AddField(
            model_name='genrefilmwork',
            name='film_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.filmwork', verbose_name='Film work'),
        ),
        migrations.AddField(
            model_name='genrefilmwork',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_film_work', to='movies.genre', verbose_name='Title'),
        ),
        migrations.AddIndex(
            model_name='genre',
            index=models.Index(fields=['description'], name='genre_idx'),
        ),
        migrations.AddField(
            model_name='filmwork',
            name='genr',
            field=models.ManyToManyField(through='movies.GenreFilmWork', to='movies.genre', verbose_name='genres'),
        ),
        migrations.AddField(
            model_name='filmwork',
            name='pers',
            field=models.ManyToManyField(through='movies.PersonFilmWork', to='movies.person', verbose_name='persons'),
        ),
        migrations.AddIndex(
            model_name='personfilmwork',
            index=models.Index(fields=['role'], name='person_film_work'),
        ),
        migrations.AddIndex(
            model_name='filmwork',
            index=models.Index(fields=['creation_date'], name='film_work_idx'),
        ),
    ]
