version: '3.9'
services:
  movies_database:
    image: postgres:13
    container_name: movies_database
    env_file:
      - .env
    ports:
      - "5432:5432"

  django_project:
    build: ./app
    image: django_admin
    container_name: django_admin
    depends_on:
      - movies_database
    volumes:
      - static_volume:/opt/app/static/
      - media_volume:/opt/app/media/
    env_file:
      - .env
    ports:
      - "8001:8000"

#  service:
#    build: ./app
#    expose:
#      - "8000"
#    depends_on:
#      - django_project

  nginx:
    image: nginx:1.22.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - ./data:/data/:ro
      - static_volume:/opt/app/static/
      - media_volume:/opt/app/media/
    depends_on:
      - django_project
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"

volumes:
  static_volume:
  media_volume:
  nginx.conf:
  configs:
